var demo_words = {
	"genre" : ["list"],
	"dramatic works" : ["stuff"],
	"contemporary" : ["today"],
	"discourse" : ["thing"],
	"inducing" : ["creating"],
	"public opinion": ["feels"],
	"influenced" : ["shape"],
	"political satire" : ["stuff"],
	"dramatic performance": ["thing"],
	"societies" : ["things"],
	"agon" : ["thing"],
	"conflict" : ["thing"],
	"dichotomy" : ["split"],
	"seldom": ["not usually"],
	"satisfactory" : ["ok"],
	"characterizes" : ["names"],
	"essential": ["first"],
	"struggle" : ["fight"],
	"societal conventions" : ["peer pressure"],
	"youth" : ["wimp"],
	"constrained" : ["stunted"],
	"engender" : ["create"],
	"very dramatic irony": ["stuff"],
	"ironic comedy" : ["other stuff"],
	"alienating" : ["redirecting"],
	"Ironic" : ["confusing"],
	"condemning" : ["rude"],
	"improbable" : ["???"],
	"Black:" : ["Dark (not racist)"]
}

